#!/usr/bin/env ruby
require 'bundler/setup'
require 'everypolitician'

parliament = Everypolitician.legislature('Uganda', 'Parliament')

File.write('EVERYPOLITICIAN_DATASOURCE', parliament.raw_data[:popolo_url])

system('git add EVERYPOLITICIAN_DATASOURCE')
system('git commit -m "Update EVERYPOLITICIAN_DATASOURCE"')
